name: Deployment Check

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  check:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Wait for deploy
        run: sleep 20

      - name: Check API
        run: |
          for i in {1..12}; do
            curl --fail https://freelance-platform-production.up.railway.app/api/tasks && exit 0
            echo "Retry API..."
            sleep 10
          done
          exit 1

      - name: Check Website
        run: |
          curl --fail https://freelance-platform-production.up.railway.app/